# Generated by Django 4.0.5 on 2022-06-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportresults_result_comparison_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportresults',
            name='total_calculated_prices',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reportresults',
            name='total_discrepancies',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reportresults',
            name='total_supplements',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reportresults',
            name='total_theorical_prices',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
