# Generated by Django 4.0.5 on 2022-06-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailsintegration',
            name='header_row',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
