# Generated by Django 4.0.5 on 2022-06-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companydetailsintegration_header_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailsintegration',
            name='column_date',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
