# Generated by Django 4.0.5 on 2022-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='transporterfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
