# Generated by Django 4.0.5 on 2022-06-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_companyfile_file_alter_transporterfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfileresult',
            name='company_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.companyfile'),
        ),
    ]
