# Generated by Django 4.0.5 on 2022-06-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('files', '0004_alter_transporterfileresults_transporter_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfile',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='transporterfile',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
