# Generated by Django 4.0.5 on 2022-06-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_annonce_incomplete', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément annonce incomplète')),
                ('supplement_retour_expediteur', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément Retour Expéditeur')),
                ('supplement_etiquette_non_conforme', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément Etiquette non-conforme')),
                ('supplement_zone_difficile_acces', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name="Supplément zone difficile d'accès")),
                ('supplement_corse', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément Corse')),
                ('supplement_manutention', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément manutention')),
                ('supplement_gt', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément GT')),
                ('supplement_carburant_routier', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément carburant routier')),
                ('supplement_frais_de_gestion', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément frais de gestion')),
                ('supplement_facture_papier', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément facture papier')),
                ('supplement_surete_colis', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément facture colis')),
                ('supplement_zone_internationale_eloignee', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément zone internationale éloignée')),
                ('supplement_surcharge_carburant_routier', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément surcharge carburant routier')),
                ('supplement_covid', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément COVID')),
                ('supplement_taxe_carbone', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Supplément taxe carbone')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.company')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.transporter')),
            ],
            options={
                'verbose_name': 'Supplément',
                'verbose_name_plural': 'Suppléments',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns_to_keep', models.JSONField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.company')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.transporter')),
            ],
            options={
                'verbose_name': 'Weight',
                'verbose_name_plural': 'Weights',
            },
        ),
        migrations.CreateModel(
            name='WeightPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.FloatField(null=True, verbose_name='Min weight')),
                ('max_weight', models.FloatField(null=True, verbose_name='Max weight')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplements.weight')),
            ],
            options={
                'verbose_name': 'Weight Price',
                'verbose_name_plural': 'Weight Prices',
            },
        ),
        migrations.CreateModel(
            name='TransporterImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_row', models.IntegerField(blank=True, null=True)),
                ('columns_to_keep', models.JSONField(blank=True, null=True)),
                ('column_price', models.JSONField(blank=True, null=True)),
                ('column_package_number', models.JSONField(blank=True, null=True)),
                ('column_prestation_type', models.JSONField(blank=True, null=True)),
                ('column_weight', models.JSONField(blank=True, null=True)),
                ('columns_supplements', models.JSONField(blank=True, null=True)),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplements.supplement')),
            ],
            options={
                'verbose_name': 'Supplément - Detail per company',
                'verbose_name_plural': 'Suppléments - Details per company',
            },
        ),
    ]
