# Generated by Django 4.0.5 on 2022-06-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporterimplementation',
            name='column_date',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
