# Generated by Django 4.0.5 on 2022-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_transporterimplementation_column_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_annonce_incomplete',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_carburant_routier',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_corse',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_covid',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_etiquette_non_conforme',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_facture_papier',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_frais_de_gestion',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_gt',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_manutention',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_retour_expediteur',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_surcharge_carburant_routier',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_surete_colis',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_taxe_carbone',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_zone_difficile_acces',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplement_zone_internationale_eloignee',
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
